from django.urls import path

from . import views

urlpatterns = [
    path('accounts/bank-accounts-by-bank/', views.bank_accounts_by_bank, name='bank_accounts_by_bank'),
    path('accounts/mobile-account-lookup/', views.mobile_account_lookup, name='mobile_account_lookup'),
    path('accounts/client-data/', views.client_data_api, name='client_data_api'),
    path('accounts/invoices/', views.invoice_list, name='invoice_list'),
    path('accounts/invoices/new/', views.invoice_create, name='invoice_create'),
    path('accounts/invoices/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('accounts/invoices/<int:pk>/edit/', views.invoice_edit, name='invoice_edit'),
    path('accounts/invoices/<int:pk>/delete/', views.invoice_delete, name='invoice_delete'),
    path('accounts/invoices/<int:pk>/pdf/', views.invoice_pdf, name='invoice_pdf'),
    path('accounts/invoices/<int:pk>/mark-paid/', views.invoice_mark_paid, name='invoice_mark_paid'),
    path('accounts/invoices/<int:pk>/update-status/', views.invoice_update_status, name='invoice_update_status'),
    path('accounts/payments/', views.payment_list, name='payment_list'),
    path('accounts/payments/new/', views.payment_create, name='payment_create'),
    path('accounts/payments/<int:pk>/', views.payment_detail, name='payment_detail'),
    path('accounts/payments/<int:pk>/edit/', views.payment_edit, name='payment_edit'),
    path('accounts/payments/<int:pk>/delete/', views.payment_delete, name='payment_delete'),
    path('accounts/expenses/', views.expense_list, name='expense_list'),
    path('accounts/expenses/new/', views.expense_create, name='expense_create'),
    path('accounts/expenses/<int:pk>/', views.expense_detail, name='expense_detail'),
    path('accounts/expenses/<int:pk>/edit/', views.expense_edit, name='expense_edit'),
    path('accounts/expenses/<int:pk>/delete/', views.expense_delete, name='expense_delete'),
    path('accounts/expense-categories/', views.expense_category_list, name='expense_category_list'),
    path('accounts/expense-categories/new/', views.expense_category_create, name='expense_category_create'),
    path('accounts/expense-categories/<int:pk>/', views.expense_category_detail, name='expense_category_detail'),
    path('accounts/expense-categories/<int:pk>/edit/', views.expense_category_edit, name='expense_category_edit'),
    path('accounts/expense-categories/<int:pk>/update-status/', views.expense_category_update_status, name='expense_category_update_status'),
    path('accounts/bank/', views.bank_account_list, name='bank_account_list'),
    path('accounts/bank/new/', views.bank_account_create, name='bank_account_create'),
    path('accounts/bank/<int:pk>/', views.bank_account_detail, name='bank_account_detail'),
    path('accounts/bank/<int:pk>/edit/', views.bank_account_edit, name='bank_account_edit'),
    path('accounts/bank/<int:pk>/toggle/', views.bank_account_toggle, name='bank_account_toggle'),
    path('accounts/bank/<int:pk>/update-status/', views.bank_account_update_status, name='bank_account_update_status'),
    path('accounts/bank/<int:pk>/delete/', views.bank_account_delete, name='bank_account_delete'),
    path('accounts/transfers/', views.transfer_list, name='transfer_list'),
    path('accounts/transfers/new/', views.transfer_create, name='transfer_create'),
    path('accounts/transfers/<int:pk>/', views.transfer_detail, name='transfer_detail'),
    path('accounts/transfers/<int:pk>/delete/', views.transfer_delete, name='transfer_delete'),
]

