# Generated by Django 5.2.16 on 2026-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leadcontact',
            options={},
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='pipeline',
            field=models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Support')], default='sales', max_length=30),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('generated', 'Generated'), ('qualified', 'Qualified'), ('presentation', 'Presentation'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='generated', max_length=30),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='lead_source',
            field=models.CharField(choices=[('none', 'None'), ('cold_call', 'Cold Call'), ('email', 'Email'), ('website', 'Website'), ('social', 'Social Media'), ('referral', 'Referral'), ('other', 'Other')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='salutation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
