# Generated by Django 5.2.16 on 2026-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_deal_options_alter_leadcontact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='contact_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal')], default='lead', max_length=10),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='lead_source',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
