# Generated by Django 5.2.16 on 2026-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadcontact_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
