# Generated by Django 5.2.16 on 2026-07-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_add_is_active_to_leadcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcontact',
            name='is_active',
        ),
    ]
