# Generated by Django 5.2.16 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_merge_old_deal_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('generated', 'Generated'), ('won', 'Won'), ('lost', 'Lost')], default='generated', max_length=30),
        ),
    ]
