# Generated by Django 5.2.16 on 2026-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_deal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='budget',
            field=models.CharField(blank=True, help_text='Initial budget estimate', max_length=100),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='followup_action',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('text', 'Text'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], default='call', max_length=20),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='lead_state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('lost', 'Lost')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
