# Generated by Django 5.2.16 on 2026-07-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_leadcontact_budget_leadcontact_followup_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontact',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('', '---'), ('attempted_contact', 'Attempted Contact'), ('contacted', 'Contacted'), ('convert_to_sale', 'Convert to Sale'), ('interested', 'Interested'), ('lost', 'Lost'), ('meeting_scheduled', 'Meeting Scheduled'), ('needs_follow_up', 'Needs Follow Up'), ('negotiation', 'Negotiation'), ('new_lead', 'New Lead'), ('not_interested', 'Not Interested'), ('proposal_sent', 'Proposal Sent')], default='new_lead', max_length=25),
        ),
    ]
