# Generated by Django 5.2.16 on 2026-07-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_leadcontact_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontact',
            name='contact_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('mid', 'Mid')], default='cold', max_length=10),
        ),
    ]
