# Generated by Django 5.2.16 on 2026-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_leadsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
