# Generated by Django 5.2.16 on 2026-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_followup_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
    ]
