# Generated by Django 5.2.16 on 2026-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('USD', 'USD ($)'), ('BDT', 'BDT (৳)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('INR', 'INR (₹)'), ('CAD', 'CAD (C$)'), ('AUD', 'AUD (A$)'), ('SGD', 'SGD (S$)'), ('MYR', 'MYR (RM)'), ('AED', 'AED (د.إ)'), ('SAR', 'SAR (﷼)'), ('JPY', 'JPY (¥)'), ('CNY', 'CNY (¥)'), ('KRW', 'KRW (₩)'), ('THB', 'THB (฿)'), ('PHP', 'PHP (₱)'), ('IDR', 'IDR (Rp)'), ('PKR', 'PKR (₨)'), ('LKR', 'LKR (Rs)'), ('NGN', 'NGN (₦)'), ('ZAR', 'ZAR (R)'), ('BRL', 'BRL (R$)'), ('MXN', 'MXN ($)'), ('TRY', 'TRY (₺)'), ('RUB', 'RUB (₽)'), ('SEK', 'SEK (kr)'), ('NOK', 'NOK (kr)'), ('DKK', 'DKK (kr)'), ('CHF', 'CHF (CHF)'), ('PLN', 'PLN (zł)')], default='USD', max_length=10)),
            ],
            options={
                'verbose_name': 'Currency Settings',
                'verbose_name_plural': 'Currency Settings',
            },
        ),
    ]
