# Generated by Django 6.0.7 on 2026-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_text',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
