# Generated by Django 5.2.16 on 2026-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sitesettings_logo_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysettings',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('BDT', 'BDT (৳)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('INR', 'INR (₹)'), ('CAD', 'CAD (C$)'), ('AUD', 'AUD (A$)'), ('SGD', 'SGD (S$)'), ('MYR', 'MYR (RM)'), ('AED', 'AED (د.إ)'), ('SAR', 'SAR (﷼)'), ('JPY', 'JPY (¥)'), ('CNY', 'CNY (¥)'), ('KRW', 'KRW (₩)'), ('THB', 'THB (฿)'), ('PHP', 'PHP (₱)'), ('IDR', 'IDR (Rp)'), ('PKR', 'PKR (₨)'), ('LKR', 'LKR (Rs)'), ('NGN', 'NGN (₦)'), ('ZAR', 'ZAR (R)'), ('BRL', 'BRL (R$)'), ('MXN', 'MXN ($)'), ('TRY', 'TRY (₺)'), ('RUB', 'RUB (₽)'), ('SEK', 'SEK (kr)'), ('NOK', 'NOK (kr)'), ('DKK', 'DKK (kr)'), ('CHF', 'CHF (CHF)'), ('PLN', 'PLN (zł)')], default='BDT', max_length=10),
        ),
    ]
