# Generated by Django 6.0.7 on 2026-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_client_lead_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='salutation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
