# Generated by Django 6.0.7 on 2026-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_salutation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Client categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('local_shop', 'Local Shop'), ('retail_shopping', 'Retail & Shopping'), ('it_technology', 'IT & Technology'), ('finance_legal', 'Finance & Legal'), ('food_restaurant', 'Food & Restaurant'), ('fashion', 'Fashion'), ('hospitality_travels', 'Hospitality & Travels'), ('real_estate_construction', 'Real Estate & Construction'), ('automotive', 'Automotive'), ('beauty_personal_care', 'Beauty & Personal Care'), ('sports_fitness', 'Sports & Fitness'), ('health_medical', 'Health & Medical'), ('business_services', 'Business & Services'), ('home_local_services', 'Home & Local Services'), ('entertainment_lifestyle', 'Entertainment & Lifestyle'), ('logistics_transport', 'Logistics & Transport'), ('architecture_engineering', 'Architecture & Engineering Consultancy'), ('agriculture', 'Agriculture')], max_length=30),
        ),
    ]
