# Generated by Django 6.0.7 on 2026-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientcategory_alter_client_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
