# Generated by Django 6.0.7 on 2026-07-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_status'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE clients_client SET status='open' WHERE status='active';",
            reverse_sql="UPDATE clients_client SET status='active' WHERE status='open';",
        ),
        migrations.RunSQL(
            sql="UPDATE clients_client SET status='closed' WHERE status='inactive';",
            reverse_sql="UPDATE clients_client SET status='inactive' WHERE status='closed';",
        ),
    ]
