# Generated by Django 5.2.16 on 2026-08-11 12:06

from django.db import migrations, models


def normalize_status(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Client.objects.filter(status__in=['open', '']).update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.RunPython(normalize_status, migrations.RunPython.noop),
    ]
