# Generated by Django 5.2.16 on 2026-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invoice_phone_invoice_received_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_from',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — $'), ('BDT', 'BDT — ৳'), ('EUR', 'EUR — €'), ('GBP', 'GBP — £'), ('INR', 'INR — ₹'), ('JPY', 'JPY — ¥'), ('CAD', 'CAD — C$'), ('AUD', 'AUD — A$'), ('AED', 'AED — د.إ'), ('SAR', 'SAR — ر.س')], default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_logos/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
