# Generated by Django 6.0.7 on 2026-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invoice_bill_from_invoice_currency_invoice_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bill_from',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — $'), ('BDT', 'BDT — ৳'), ('EUR', 'EUR — €'), ('GBP', 'GBP — £'), ('INR', 'INR — ₹'), ('JPY', 'JPY — ¥'), ('CAD', 'CAD — C$'), ('AUD', 'AUD — A$'), ('AED', 'AED — د.إ'), ('SAR', 'SAR — ر.س')], default='BDT', max_length=5),
        ),
    ]
