# Generated by Django 6.0.7 on 2026-07-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invoice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
