# Generated by Django 6.0.7 on 2026-07-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_edited_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.bankaccount'),
        ),
    ]
