# Generated by Django 6.0.7 on 2026-07-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bankaccount_details_payment_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.bankaccount'),
        ),
    ]
