# Generated by Django 6.0.7 on 2026-07-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_expense_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('online', 'Online'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='MobileAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card')], max_length=10)),
                ('number', models.CharField(max_length=50)),
                ('holder_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('account_type', 'number')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.mobileaccount'),
        ),
    ]
