# Generated by Django 6.0.7 on 2026-07-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_payment_method_mobileaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mobile_account',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bank_account',
            new_name='account',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_bank',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_holder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='category',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='holder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='mobile_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('agent', 'Agent')], default='personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='MobileAccount',
        ),
    ]
