# Generated by Django 6.0.7 on 2026-07-30 09:55

from django.db import migrations, models


def seed_types(apps, schema_editor):
    AccountType = apps.get_model('accounts', 'AccountType')
    for key, label in [('bank', 'Bank'), ('mobile', 'Mobile Banking'), ('cash', 'Cash')]:
        AccountType.objects.get_or_create(key=key, defaults={'label': label})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_bankaccount_card_holder_name_bankaccount_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='account_type',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(seed_types),
    ]
