# Generated by Django 5.2.16 on 2026-08-05 10:57

from django.db import migrations, models


def backfill_expense_method(apps, schema_editor):
    Expense = apps.get_model('accounts', 'Expense')
    for exp in Expense.objects.select_related('bank_account__account_category').all():
        acct = exp.bank_account
        if acct and acct.account_category:
            exp.method = acct.account_category.name.lower()
        else:
            exp.method = 'cash'
        exp.save(update_fields=['method'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cheque', 'Cheque'), ('card', 'Card'), ('online', 'Online'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cheque', 'Cheque'), ('card', 'Card'), ('online', 'Online'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay')], default='cash', max_length=20),
        ),
        migrations.RunPython(backfill_expense_method, migrations.RunPython.noop),
    ]
