# Generated by Django 5.2.16 on 2026-08-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_expense_method_alter_payment_method'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: (
                apps.get_model('accounts', 'Payment').objects.filter(method='bank_transfer').update(method='bank'),
                apps.get_model('accounts', 'Expense').objects.filter(method='bank_transfer').update(method='bank'),
            )[1],
            reverse_code=migrations.RunPython.noop,
        ),
    ]
