# Generated by Django 5.2.16 on 2026-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bank_transfer_to_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('check', 'Check'), ('cheque', 'Cheque'), ('card', 'Card'), ('online', 'Online'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('check', 'Check'), ('cheque', 'Cheque'), ('card', 'Card'), ('online', 'Online'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay')], default='cash', max_length=20),
        ),
    ]
