# Generated by Django 5.2.16 on 2026-09-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_fix_uncategorized_accounts'),
        ('clients', '0011_alter_client_status'),
        ('leads', '0014_alter_followup_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('valid_days', models.IntegerField(default=15)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('subject', models.CharField(default='Quotation for CRM & HRM Software Solution', max_length=300)),
                ('intro_letter', models.TextField(blank=True, default='Thank you for your interest in our CRM & HRM solution. Based on your requirements, we are pleased to submit the following quotation for our CRM & HRM Software Solution.')),
                ('crm_features', models.JSONField(blank=True, default=list)),
                ('hrm_features', models.JSONField(blank=True, default=list)),
                ('mobile_app_features', models.JSONField(blank=True, default=list)),
                ('system_features', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('security_features', models.JSONField(blank=True, default=list)),
                ('training_support', models.JSONField(blank=True, default=list)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('pricing_plans', models.JSONField(blank=True, default=list)),
                ('payment_terms', models.TextField(blank=True, default='• One-Time License:\n  - 40% Advance\n  - 30% Before Testing\n  - 30% Before Final Delivery\n\n• SaaS:\n  - Setup Fee: 100% Advance\n  - Monthly Subscription: Payable in Advance')),
                ('delivery_terms', models.TextField(blank=True, default='• Deployment Time: 7–30 Working Days after confirmation\n• Training: Basic system training included\n• Support: Standard technical support included')),
                ('terms_conditions', models.TextField(blank=True, default='• Monthly subscription fee payable in advance\n• SaaS access will be activated after payment confirmation\n• Any additional customization will be charged separately\n• Client will provide Domain, Hosting and Console account (Not for SaaS)')),
                ('warranty', models.TextField(blank=True, default='• 3 Months Free Bug Fix Warranty (One-Time License)\n• SaaS Customers receive free updates during the active subscription.')),
                ('not_included', models.TextField(blank=True, default='• Third-party API Charges\n• SMS Gateway Charges\n• Domain & Hosting Charges (One-Time License)\n• Google Play & Apple Developer Fees')),
                ('why_danpite', models.TextField(blank=True, default='✓ Custom Software Development\n✓ Modern UI/UX\n✓ Secure Architecture\n✓ Lifetime Scalability\n✓ Dedicated Support')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD — $'), ('BDT', 'BDT — ৳'), ('EUR', 'EUR — €'), ('GBP', 'GBP — £'), ('INR', 'INR — ₹'), ('JPY', 'JPY — ¥'), ('CAD', 'CAD — C$'), ('AUD', 'AUD — A$'), ('AED', 'AED — د.إ'), ('SAR', 'SAR — ر.س')], default='BDT', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='leads.leadcontact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quotation_date', '-id'],
            },
        ),
    ]
