# Generated by Django 5.2.16 on 2026-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='feature_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
