# Generated by Django 5.2.16 on 2026-09-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_quotation_feature_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='custom_terms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
