# Generated by Django 5.2.16 on 2026-09-02 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_quotation_custom_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='terms_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('BDT', 'BDT (৳)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='BDT', max_length=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='delivery_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='intro_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='not_included',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='warranty',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='why_danpite',
            field=models.TextField(blank=True, default=''),
        ),
    ]
